### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by n0l3r** [n0l3r/Pong-Plus#9]
General:
- [x] Wireframe
- [x] Cursor
- [x] Export semua assets  

Menu:
- [x] Main menu
- [x] About
- [x] Play
- [x] Info

In-Game:
- [x] Board
- [x] Pause button & menu
- [x] paddle
- [x] Ball
- [x] Winner Game

**Comment by hfdzz** [comment]
About sama info blom ada isinya
Power up blom ada

**Comment by n0l3r** [comment]
> About sama info blom ada isinya Power up blom ada

okey sung saja dilengkapi design info terkait item yang ada

**Comment by n0l3r** [comment]
@vinsensiusrobby15 @hfdzz ini masih belum ada page winner, itu udah w tambahin ke task yakkk
